# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19MknVRWzP6FLfGJB-L90tRGQUJv6PIMT
"""

from google.colab import files
uploaded = files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
DATA_DIR = "/content/olist"

!kaggle datasets download -d olistbr/brazilian-ecommerce

!mkdir -p /content/olist
!unzip -o brazilian-ecommerce.zip -d /content/olist

import os

print(os.listdir("/content/olist"))

DATA_DIR = "/content/olist"

orders      = pd.read_csv(f"{DATA_DIR}/olist_orders_dataset.csv")
items       = pd.read_csv(f"{DATA_DIR}/olist_order_items_dataset.csv")
payments    = pd.read_csv(f"{DATA_DIR}/olist_order_payments_dataset.csv")
reviews     = pd.read_csv(f"{DATA_DIR}/olist_order_reviews_dataset.csv")
customers   = pd.read_csv(f"{DATA_DIR}/olist_customers_dataset.csv")
products    = pd.read_csv(f"{DATA_DIR}/olist_products_dataset.csv")
sellers     = pd.read_csv(f"{DATA_DIR}/olist_sellers_dataset.csv")
geolocation = pd.read_csv(f"{DATA_DIR}/olist_geolocation_dataset.csv")
cat_trans   = pd.read_csv(f"{DATA_DIR}/product_category_name_translation.csv")

for name, df in [
    ("orders", orders),
    ("items", items),
    ("payments", payments),
    ("reviews", reviews),
    ("customers", customers),
    ("products", products),
    ("sellers", sellers),
    ("geolocation", geolocation)
]:
    print(f"{name}: {df.shape[0]:,} rows x {df.shape[1]} columns")

print("Missing values in orders:\n", orders.isnull().sum(), "\n")
print("Missing values in reviews:\n", reviews.isnull().sum(), "\n")
print("Missing values in products:\n", products.isnull().sum(), "\n")
print("Duplicate order rows:", orders.duplicated().sum())
print("Duplicate order_id in items:", items['order_id'].duplicated().sum(), "(expected — multiple items per order)")
orders.dtypes

date_cols = ['order_purchase_timestamp','order_approved_at','order_delivered_carrier_date',
             'order_delivered_customer_date','order_estimated_delivery_date']
for c in date_cols:
    orders[c] = pd.to_datetime(orders[c], errors='coerce')

orders = orders.drop_duplicates()
customers = customers.drop_duplicates()


delivered = orders[orders['order_status'] == 'delivered'].copy()

delivered['delivery_days'] = (delivered['order_delivered_customer_date']
                               - delivered['order_purchase_timestamp']).dt.days
delivered['delay_days'] = (delivered['order_delivered_customer_date']
                            - delivered['order_estimated_delivery_date']).dt.days
delivered['is_late'] = delivered['delay_days'] > 0


merged = (delivered
    .merge(items, on='order_id', how='left')
    .merge(products, on='product_id', how='left')
    .merge(cat_trans, on='product_category_name', how='left')
    .merge(reviews[['order_id','review_score']], on='order_id', how='left')
    .merge(customers[['customer_id','customer_state','customer_city']], on='customer_id', how='left')
)


merged['product_category_name_english'] = merged['product_category_name_english'].fillna('unknown')

order_value = payments.groupby('order_id')['payment_value'].sum().reset_index()
merged = merged.merge(order_value, on='order_id', how='left')


q1, q3 = merged['price'].quantile([0.25, 0.75])
iqr = q3 - q1
price_upper = q3 + 1.5 * iqr
outliers = merged[merged['price'] > price_upper]
print(f"Price outliers flagged: {len(outliers):,} rows out of {len(merged):,}")

print("Processed dataset shape:", merged.shape)
merged.head()

cat_revenue = merged.groupby('product_category_name_english')['payment_value'].sum().sort_values(ascending=False)
print(cat_revenue.head(10))

plt.figure(figsize=(10,5))
cat_revenue.head(10).plot(kind='bar')
plt.title('Top 10 Categories by Revenue')
plt.ylabel('Total Revenue (R$)')
plt.tight_layout()
plt.show()

delay_vs_review = merged.groupby('is_late')['review_score'].mean()
print(delay_vs_review)

plt.figure(figsize=(6,4))
delay_vs_review.plot(kind='bar', color=['green','red'])
plt.title('Average Review Score: On-Time vs Late Deliveries')
plt.ylabel('Average Review Score')
plt.xticks([0,1], ['On Time','Late'], rotation=0)
plt.tight_layout()
plt.show()

state_stats = merged.groupby('customer_state').agg(
    revenue=('payment_value','sum'),
    orders=('order_id','nunique'),
    avg_review=('review_score','mean')
).sort_values('revenue', ascending=False)
state_stats['avg_order_value'] = state_stats['revenue'] / state_stats['orders']
print(state_stats.head(10))

merged['order_month'] = merged['order_purchase_timestamp'].dt.to_period('M')
monthly_revenue = merged.groupby('order_month')['payment_value'].sum()

plt.figure(figsize=(12,5))
monthly_revenue.plot()
plt.title('Monthly Revenue Trend')
plt.ylabel('Revenue (R$)')
plt.tight_layout()
plt.show()

cat_summary = merged.groupby('product_category_name_english').agg(
    revenue=('payment_value','sum'),
    avg_review=('review_score','mean'),
    avg_delivery_days=('delivery_days','mean'),
    orders=('order_id','nunique')
).sort_values('revenue', ascending=False)
print(cat_summary.head(15))

category_to_check = "REPLACE_WITH_CATEGORY_NAME"
seller_breakdown = merged[merged['product_category_name_english'] == category_to_check].groupby('seller_id').agg(
    orders=('order_id','nunique'),
    avg_review=('review_score','mean')
).sort_values('orders', ascending=False)
print(seller_breakdown.head(10))

merged.to_csv('/content/processed_data.csv', index=False)
from google.colab import files
files.download('/content/processed_data.csv')